=== jdemmith/demmith-jacob-CSC380/ws_lunch/JDemmith_REST/build/classes/restaurants.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/restaurants"
	xmlns:tns="http://www.example.org/restaurants" elementFormDefault="qualified">
	<element name="Service">
		<complexType>
			<sequence>
				<element name="restaurant" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="Name" type="string"/>
							<element name="Id"/>
							<element name="Menu">
								<complexType>
									<sequence>
										<element name="Item" maxOccurs="unbounded">
											<complexType>
												<sequence>
													<element name="Name" type="string" />
													<element name="Price" type="double" />
												</sequence>
											</complexType>
										</element>
									</sequence>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== jdemmith/demmith-jacob-CSC380/ws_lunch/JDemmith_REST/build/classes/restaurants.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Service xmlns:tns="http://www.example.org/restaurants" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/restaurants restaurants.xsd ">
  <tns:restaurant>
    <tns:Name>Subway</tns:Name>
    <tns:Id>0</tns:Id>
    <tns:Menu>
      <tns:Item>
        <tns:Name>Sub</tns:Name>
        <tns:Price>5.0</tns:Price>
      </tns:Item>
      <tns:Item>
        <tns:Name>Pizza</tns:Name>
        <tns:Price>3.5</tns:Price>
      </tns:Item>
    </tns:Menu>
  </tns:restaurant>
  <tns:restaurant>
    <tns:Name>Jimmy John's</tns:Name>
    <tns:Id>1</tns:Id>
    <tns:Menu>
      <tns:Item>
        <tns:Name>Sub</tns:Name>
        <tns:Price>8.0</tns:Price>
      </tns:Item>
    </tns:Menu>
  </tns:restaurant>
</tns:Service>
